### ISSUE TITLE
Issue with message acknowledgement/completion/ownership in current design?

### ISSUE THREAD

**Issue by drub0y** [christopherread/Obvs#14]
Right now Obvs provides an abstraction over the transport and provides you streams of data types via `IObservable<IMessage>` and all the other `IMessage` subtypes. This is nice because the framework allows the apps to just work with its data types and there is little "pollution" of those types from Obvs, but, because all of the messaging semantics have been stripped away, the application loses any kind of responsibility/control over message acknowledgement/completion which is a big problem in the world of competing consumers and fault tolerance.

Suppose a scenario where there is a subscriber for processing `CreateUser` commands which fails half way through because of an intermittent connectivity issue with its backend data store, so it just throws an exception. That command shouldn't be lost, it should show back up on the queue after a certain amount of time so it can be retried again later.

Also consider a scenario where you have long running processes as the result of a command. You don't want to use message receipts that are too long lived in case the instance that was handling the command crashes, so maybe you have a 5min receipt that you renew each step along the way to retain ownership over the message so its not relisted on the queue. How can you do this when all you're working with is `IMessage` though?

Or, even just consider the very simple scenario of a message being received, but the power going out on the node half way through processing the message. Obviously you don't want that message lost forever just because Joe from IT tripped over a plug in your data center. :)

In the `Obvs.ActiveMQ` transport implementation, for example, I notice [you auto-acknowledge the message right after you deserialize it](https://github.com/inter8ection/Obvs.ActiveMQ/blob/master/Obvs.ActiveMQ/MessageSource.cs#L94). That seems super early as you haven't even delivered it to subscriber(s) yet. In my of `Obvs.AzureServiceBus` right now I am calling `OnNext` to deliver the message to any subscribers first and then, only if that doesn't result in an exception, do [I auto-complete the message](https://github.com/drub0y/Obvs.AzureServiceBus/blob/master/Obvs.AzureServiceBus/MessageSource.cs#L68).

Have you given this any thought previously??? I ran into the very same design issue in my own SB that I had been working on before I abandoned it in favor of Obvs. I'm not sure what the best solution is. Spitballing...
- You _wouldn't_ want to put these control methods on `IMessage` because then now you put behavior onto your data types and you're going to end up forcing everyone to inherit from a base class.
- One approach I had thought of is was introducing another interface called `IMessageControl` like:

``` C#
public interface IMessageControl<out TMessage>
        where TMessage : IMessage
{
    TMessage Message
    {
        get;
    }
    void Abandon();
    void Complete();
    void Renew(TimeSpan renewTime);
    void Reject(string reason);        
}
```

Then all the observable streams become `IObservable<IMessageControl<TMessage>>` based instead. The problem with this is that it forces this upon everyone using the framework even if they wanted to use a non-safe/enterprisey approach to messaging that didn't have message control. So I sort of reject this based on that.
- The last approach would be to have the message control methods on some other class (the  `IServiceBus/IServiceBusClient` maybe?) themselves so people would still receive just `MyCommand` instances, but could acknowledge them something like:

``` C#
serviceBus.Commands.Subscribe(c =>
{
    // whatever logic

    serviceBus.Complete(c);
}
```

Maybe directly off the bus interfaces isn't a great idea either though, maybe you get a message controller off of the bus somehow instead?

Any thoughts? Am I missing something obvious that would make this way easier to solve?

**Comment by inter8ection** [comment]
Coincidentally a few weeks ago I was speaking to Lee Campbell, the author of IntroToRx.com and speaker at last year's React conference, about this issue in person and he didn't think Rx was a good fit for transactional queues, and you can see why for the reasons you outline above, and because there is no back-pressure mechanism, it's very one-way.

My experience has been the most common errors are deserialization ones, so I just handle that case in ActiveMQ. You're right you can also do it after OnNext, but I'm not sure that will work as expected if your subscriber is observing on another scheduler. In general you aren't supposed to be doing a lot of work in the OnNext and block in there, but I guess that's the caller's choice. That said, it doesn't hurt to at least wait for the OnNext before ack'ing.

I did have an improvement in mind for the AMQ implementation, which was to stick messages onto a ".Errors" error queue rather than just drop them on the floor.

Both of your suggested solutions have merit, but as you say I'm not overly keen on 'polluting' the main Obvs interfaces with them, as the design intent for Obvs is that it be clean and simple, letting the caller worry about failure scenarios to handle rather than trying to build them in (e.g. explicitly publishing back onto the queue, an error queue, or alerting/logging failure).

> Maybe directly off the bus interfaces isn't a great idea either though, maybe you get a message controller off of the bus somehow instead?

Yes this could be a slightly less 'dirty' option, and something you could add as a fluent config option on the Azure SB endpoint to pass in your own MessageController if you really felt you needed it. It all feels like a bit of a leaky abstraction though, so I don't know what the right answer is.

**Comment by drub0y** [comment]
> Coincidentally a few weeks ago I was speaking to Lee Campbell, the author of IntroToRx.com and speaker at last year's React conference, about this issue in person and he didn't think Rx was a good fit for transactional queues, and you can see why for the reasons you outline above, and because there is no back-pressure mechanism, it's very one-way.

Yes, in my limited experience with building various abstractions over transactional queues with Rx I've come to the same conclusion. It's ultimately fire and forget, so to solve the problem we're talking about here you would *have* to have offer some kind of message control.

> You're right you can also do it after OnNext, but I'm not sure that will work as expected if your subscriber is observing on another scheduler. In general you aren't supposed to be doing a lot of work in the OnNext and block in there, but I guess that's the caller's choice. That said, it doesn't hurt to at least wait for the OnNext before ack'ing.

Yeah, totally. The rules of Rx pretty much state that you shouldn't ever really take any kind of  dependency on `OnNext` throwing. I figured it's at least one step further, but if I end up implementing message control I will likely just get rid of auto-completion. Either you pick `PeekLock` mode and your app has to take control (how exactly is to still be determined) or you pick `ReceiveAndDelete` and it gets popped off and that's it... you'd have put it back yourself if you want to.

> It all feels like a bit of a leaky abstraction though, so I don't know what the right answer is.

I agree, it totally does. The problem is very real for us though, so I'll give it some more thought and see if I can come up with anything less fugly.

**Comment by inter8ection** [comment]
You could have something similar to your `IMessageControl` interface, but instead make it extend IMessage, e.g. `ITransactionalMessage<TMessage> : IMessage`, so you can use OfType<ITransactionalMessage>() to get at them without changing the Obvs interfaces.

**Comment by christopherread** [comment]
May be revisited in future, but closing this issue for now.
