### ISSUE TITLE
Add support for Azure Service Bus Queues

### ISSUE THREAD

**Issue by drub0y** [christopherread/Obvs#2]
It would be great to add support for Azure Service Bus Queues as a message transport.
- [x] Azure ServiceBus Queue based `IMessagePublisher` implementation
- [x] Azure ServiceBus Queue based `IMessageSource` implementation
- [x] Azure ServiceBus Queue fluent configuration extension methods

**Comment by drub0y** [comment]
Ok, so I've started this work [here in my Obvs.AzureServiceBus repo](https://github.com/drub0y/Obvs.AzureServiceBus).  The beginnings of the publisher and source implementations are there and I've started working on some unit tests for those. I'm not sure I'm going to stick with `MessageSender/Receiver` being passed into the constructor because they cannot be easily mocked (the Azure SB framework isn't very friendly to mocking). I actually have another lib of my own ([HackedBrain.Azure](https://github.com/HackedBrain/HackedBrain.Azure)) that provides extensions to turn the various messaging entity types into `IObservable` streams. I'm thinking I might just piggy back off of that work so that I don't have to provide the same abstractions in the Obvs.AzureServiceBus lib itself... at least to get started. If we were to later decide we wanted to eliminate that dependency we can.

After starting to get some hands on experience with the internals, I have some thoughts on core Obsv framework stuff that I guess I'll raise as separate issues about to get some discussion going.

**Comment by inter8ection** [comment]
Looks good, I definitely don't have enough unit tests in the other implementations yet, having just used explicit integration tests to see if they were working... but I should probably add them at some point. I was thinking I'd like to add some benchmarking at some point - partly curiosity but also because it would be of use to compare transports, and also validate performance improvements later on.

No worries about the dependency on HackedBrain.Azure if it makes things smoother to get started.

There are some classes in the core Obvs library which are leftovers from when it was part of another internal project, and we might be able to remove them at some point. My thought was trying to give people the option to compose things together in their own way and use the sources/publishers directly if they didn't want the whole ServiceBus.

**Comment by inter8ection** [comment]
Hey @drub0y, any chance we can do a full v1.0 release and close the issue?
