### ISSUE TITLE
[Question] Is `IObservable` filtering applied on the client or server?

### ISSUE THREAD

**Issue by julealgon** [christopherread/Obvs#39]
I'm interested in the library but was wondering what happens when you filter a given `IObservable<T>` before subscribing: is filtering (and all RX operators) applied on the client side (that is, after the message was already received), or is it somehow performed on the sender, before it is sent?

Regardless of the answer here, I'd suggest updating the documentation with this for future reference.

**Comment by christopherread** [comment]
Hello Juliano, thanks for the question. The quick answer is: all RX operators are applied client side.

This is a constraint of RX rather than a shortcoming of Obvs, as there is no way for the underlying observable to know what filters you are applying. Obvs does however _only_ subscribe to the transport once there is at least one client-side subscriber, and unsubscribes once all RX subscriptions are dropped.

Each Obvs service gets its own topics:
- MyService.Commands
- MyService.Events
- MyService.Requests
- MyService.Responses

So my recommendation is to design your microservices small enough, then no messages will be unnecessarily consumed from the message transport.

This library was designed as the core transport layer for a large complex real-time trading system, and is not the bottleneck. Also, remember the rule of: don't distribute if you don't have to, keep what you can in-process. Obvs supports a local in-process bus as well.

**Comment by julealgon** [comment]
Thanks for the prompt response.

I understand the unfortunate constraints here. Our use case scenario involves a very broad event, that needs to be filtered down heavily by a third party consumer. The filtering is complex and not part of our domain, and the client wants to have full control of this filtering which to top it of, changes from time to time. 

- Designing any hardcoded microservice to pre-filter the events in their stead increases architectural load on us
- Designing something that can be completely configurable but still run on our side is extremely complex
- Pushing all events to their client and asking them to filter there would create unnecessary network traffic, which as you can tell is highly undesirable.

As a big fan of Rx, I'll still take a look at the library to see what/if we can use some of its components, but I'm starting to think we'll need a highly customized solution to fit our needs.

**Comment by christopherread** [comment]
Hey, yes that does sound like a specific scenario. You can use Obvs MessageSource and MessagePublisher classes directly as building blocks if they would help you.

Taking a step back, the Obvs design does allow for custom service endpoints (see the readme) that would allow you _abstract_ the customised 3rd party integration behind an ```IServiceEndpointClient``` and then use Obvs for your internal microservice interactions, allowing a consistent approach.
